name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [adopt@1.8]
        scala: ['2.12', '2.13']
        include:
          - scala: '2.12'
            scala-version: 2.12.14
          - scala: '2.13'
            scala-version: 2.13.6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdk }}

      - name: Setup Tor
        uses: tor-actions/setup-tor@v1.0.0

      - name: Check formatting
        run: sbt "++${{ matrix.scala-version }} scalafmtCheckAll" scalafmtSbtCheck

      - name: Compile
        run: sbt "++${{ matrix.scala-version }} compile"

      - name: Run tests
        run: sbt coverage "++${{ matrix.scala-version }} test"

      - name: Upload coverage data to Coveralls
        run: sbt ++${{ matrix.scala-version }} coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala-version }}

      - name: Check mdoc output
        if: matrix.scala == '2.12'
        run: >
          sbt ++${{ matrix.scala-version }} mdoc &&
          git diff --exit-code
